### ISSUE TITLE
Does not work with react native 0.65

### ISSUE THREAD

**Issue by Erfan1398** [jmwind/bouncifyrn#4]
Does not work with react native 0.65, I almost did everything but couldn't compile it

**Comment by jmwind** [comment]
Last upgrade was 0.61.1. Want to help upgrade to latest?

**Comment by zack403** [comment]
> Last upgrade was 0.61.1. Want to help upgrade to latest?

yes i would like to

**Comment by jmwind** [comment]
Latest commit upgrades to react native 0.66. Mostly works, there are a few issues and warnings here and there to fix. 

More testing in simulator and then time to install on phone and beat my high score :)
